// Lightweight rule-based POS tagger. Used to build deterministic
// (no-LLM) recall-ladder masks for the Adjectives / Nouns / Verbs rungs.
//
// Quality bar: the goal is "good enough for masking-as-recall-practice".
// False positives (e.g. tagging a noun as a verb because it ends in -ed
// like "wicked") are acceptable — the worst case is a mildly mis-curated
// recall exercise, not broken text.

const FUNCTION_WORDS = new Set([
  // articles
  'a',
  'an',
  'the',
  // personal / possessive / reflexive pronouns
  'i',
  'me',
  'my',
  'mine',
  'myself',
  'you',
  'your',
  'yours',
  'yourself',
  'yourselves',
  'he',
  'him',
  'his',
  'himself',
  'she',
  'her',
  'hers',
  'herself',
  'it',
  'its',
  'itself',
  'we',
  'us',
  'our',
  'ours',
  'ourselves',
  'they',
  'them',
  'their',
  'theirs',
  'themselves',
  // demonstratives / interrogatives / relatives
  'this',
  'that',
  'these',
  'those',
  'who',
  'whom',
  'whose',
  'which',
  'what',
  'whatever',
  'whoever',
  // be / have / do (all inflections — these can be auxiliaries OR copulas)
  'am',
  'is',
  'are',
  'was',
  'were',
  'be',
  'been',
  'being',
  'have',
  'has',
  'had',
  'having',
  'do',
  'does',
  'did',
  'doing',
  'done',
  // modals
  'will',
  'would',
  'shall',
  'should',
  'can',
  'could',
  'may',
  'might',
  'must',
  'ought',
  // common prepositions
  'in',
  'on',
  'at',
  'to',
  'from',
  'of',
  'for',
  'with',
  'by',
  'about',
  'against',
  'between',
  'into',
  'through',
  'during',
  'before',
  'after',
  'above',
  'below',
  'under',
  'over',
  'up',
  'down',
  'out',
  'off',
  'as',
  'than',
  'per',
  'via',
  'upon',
  'within',
  'without',
  'across',
  'along',
  'around',
  'beyond',
  'inside',
  'outside',
  'behind',
  'beneath',
  // conjunctions / discourse markers
  'and',
  'or',
  'but',
  'so',
  'yet',
  'nor',
  'because',
  'although',
  'though',
  'while',
  'whilst',
  'since',
  'if',
  'unless',
  'when',
  'where',
  'until',
  'whether',
  'whereas',
  'however',
  'therefore',
  'moreover',
  'furthermore',
  'nevertheless',
  'meanwhile',
  'instead',
  // quantifiers / determiners / numerals
  'all',
  'some',
  'any',
  'each',
  'every',
  'no',
  'none',
  'few',
  'many',
  'most',
  'much',
  'more',
  'less',
  'least',
  'several',
  'enough',
  'such',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'both',
  'either',
  'neither',
  // negation / common adverbs that aren't content
  'not',
  'never',
  'always',
  'often',
  'sometimes',
  'usually',
  'just',
  'only',
  'even',
  'also',
  'too',
  'very',
  'quite',
  'rather',
  // pointers
  'there',
  'here',
  'then',
]);

// Common irregular verbs — these don't pattern-match by suffix.
const KNOWN_VERBS = new Set([
  'go',
  'goes',
  'went',
  'gone',
  'going',
  'say',
  'says',
  'said',
  'saying',
  'see',
  'sees',
  'saw',
  'seen',
  'seeing',
  'come',
  'comes',
  'came',
  'coming',
  'take',
  'takes',
  'took',
  'taken',
  'taking',
  'make',
  'makes',
  'made',
  'making',
  'find',
  'finds',
  'found',
  'finding',
  'give',
  'gives',
  'gave',
  'given',
  'giving',
  'know',
  'knows',
  'knew',
  'known',
  'knowing',
  'think',
  'thinks',
  'thought',
  'thinking',
  'feel',
  'feels',
  'felt',
  'feeling',
  'tell',
  'tells',
  'told',
  'telling',
  'become',
  'becomes',
  'became',
  'becoming',
  'leave',
  'leaves',
  'left',
  'leaving',
  'put',
  'puts',
  'putting',
  'mean',
  'means',
  'meant',
  'meaning',
  'keep',
  'keeps',
  'kept',
  'keeping',
  'let',
  'lets',
  'letting',
  'begin',
  'begins',
  'began',
  'begun',
  'beginning',
  'seem',
  'seems',
  'seemed',
  'seeming',
  'show',
  'shows',
  'showed',
  'shown',
  'showing',
  'try',
  'tries',
  'tried',
  'trying',
  'call',
  'calls',
  'called',
  'calling',
  'ask',
  'asks',
  'asked',
  'asking',
  'need',
  'needs',
  'needed',
  'needing',
  'work',
  'works',
  'worked',
  'working',
  'use',
  'uses',
  'used',
  'using',
  'want',
  'wants',
  'wanted',
  'wanting',
  'happen',
  'happens',
  'happened',
  'happening',
  'include',
  'includes',
  'included',
  'including',
  'get',
  'gets',
  'got',
  'gotten',
  'getting',
  'run',
  'runs',
  'ran',
  'running',
  'bring',
  'brings',
  'brought',
  'bringing',
  'write',
  'writes',
  'wrote',
  'written',
  'writing',
  'read',
  'reads',
  'reading',
  'speak',
  'speaks',
  'spoke',
  'spoken',
  'speaking',
  'hear',
  'hears',
  'heard',
  'hearing',
  'send',
  'sends',
  'sent',
  'sending',
  'meet',
  'meets',
  'met',
  'meeting',
  'pay',
  'pays',
  'paid',
  'paying',
  'sit',
  'sits',
  'sat',
  'sitting',
  'stand',
  'stands',
  'stood',
  'standing',
  'lose',
  'loses',
  'lost',
  'losing',
  'win',
  'wins',
  'won',
  'winning',
  'eat',
  'eats',
  'ate',
  'eaten',
  'eating',
  'drink',
  'drinks',
  'drank',
  'drunk',
  'drinking',
  'buy',
  'buys',
  'bought',
  'buying',
  'sell',
  'sells',
  'sold',
  'selling',
  'choose',
  'chooses',
  'chose',
  'chosen',
  'choosing',
  'decide',
  'decides',
  'decided',
  'deciding',
  'discuss',
  'discusses',
  'discussed',
  'discussing',
  'occur',
  'occurs',
  'occurred',
  'occurring',
  'happen',
  'happens',
  'happened',
  'happening',
]);

const KNOWN_ADJECTIVES = new Set([
  'good',
  'bad',
  'big',
  'small',
  'large',
  'little',
  'long',
  'short',
  'new',
  'old',
  'high',
  'low',
  'right',
  'wrong',
  'first',
  'last',
  'next',
  'main',
  'real',
  'true',
  'false',
  'free',
  'open',
  'closed',
  'public',
  'private',
  'full',
  'empty',
  'easy',
  'hard',
  'soft',
  'best',
  'better',
  'worse',
  'worst',
  'same',
  'different',
  'similar',
  'illegal',
  'legal',
  'criminal',
  'civil',
  'personal',
  'social',
  'fake',
  'genuine',
  'common',
  'rare',
  'special',
  'general',
  'young',
  'old',
  'fast',
  'slow',
  'quick',
  'late',
  'early',
  'happy',
  'sad',
  'angry',
  'calm',
  'busy',
  'free',
  'red',
  'blue',
  'green',
  'yellow',
  'black',
  'white',
  'gray',
  'brown',
  'dark',
  'light',
  'bright',
  'clear',
  'cloudy',
  'hot',
  'cold',
  'warm',
  'cool',
  'wet',
  'dry',
  'rich',
  'poor',
  'strong',
  'weak',
  'safe',
  'dangerous',
  'important',
  'simple',
  'complex',
  'final',
  'main',
]);

// `-ly` words that are NOT adverbs. These ride the suffix heuristic
// otherwise and would get mis-tagged. Adjectives like `early`, `lonely`,
// `friendly` etc. that ARE in KNOWN_ADJECTIVES never reach the adverb
// rule — they short-circuit on the known-set check above. This list
// captures the remaining false positives, mostly nouns and a few
// adjectives the dictionary doesn't cover.
const ADVERB_EXCLUDE = new Set([
  // nouns/names that happen to end in -ly
  'family',
  'belly',
  'jolly',
  'holy',
  'rally',
  'kelly',
  'sally',
  'lily',
  'billy',
  'bully',
  'molly',
  'jelly',
  'fly',
  'apply',
  'supply',
  'imply',
  'rely',
  'reply',
  // adjectives that end in -ly but aren't adverbs
  'silly',
  'lonely',
  'lovely',
  'friendly',
  'daily',
  'weekly',
  'monthly',
  'yearly',
  'hourly',
  'godly',
  'oily',
  'ugly',
  'manly',
  'womanly',
  'orderly',
  'leisurely',
  'kindly',
  // -le-stem adjectives forming -ly without being adverbs (the most common
  // false-positive cluster in the rule-based tagger)
  'bubbly',
  'wobbly',
  'prickly',
  'crinkly',
  'wiggly',
  'giggly',
  'curly',
  'wrinkly',
  'crumbly',
  'jiggly',
  'sparkly',
  'crackly',
  'squiggly',
  'gnarly',
  'ghastly',
  'ghostly',
  'beastly',
  'costly',
  'deadly',
  'deathly',
  'earthly',
  'heavenly',
  'worldly',
  'homely',
  'comely',
  'cuddly',
  'wiggly',
  'measly',
  // -ly relational adjectives (motherly, fatherly, ...)
  'motherly',
  'fatherly',
  'brotherly',
  'sisterly',
  'neighborly',
  'scholarly',
  'princely',
  'kingly',
  'knightly',
  // verbs ending in -ly
  'multiply',
]);

export function classifyWord(word) {
  const lower = word.toLowerCase();
  if (FUNCTION_WORDS.has(lower)) return 'function';
  if (KNOWN_ADJECTIVES.has(lower)) return 'adjective';
  if (KNOWN_VERBS.has(lower)) return 'verb';

  // Adverb heuristic — `-ly` ending with length >= 5, modulo the small
  // exclude set above. Checked before other suffix rules so words like
  // `quickly`, `carefully`, `obviously` route to adverb instead of
  // falling through to the noun default.
  if (/ly$/.test(lower) && lower.length >= 5 && !ADVERB_EXCLUDE.has(lower)) {
    return 'adverb';
  }

  // Suffix heuristics. Order matters: adjective patterns first (more
  // distinctive), then noun (more distinctive than verb), then verb.
  // Length guards prevent matches on tiny inflected stems.
  if (
    /(?:ful|less|ous|ive|ible|able|ic|ish)$/.test(lower) &&
    lower.length > 4
  ) {
    return 'adjective';
  }
  if (
    /(?:tion|sion|ness|ment|ity|ism|ence|ance|hood|ship)$/.test(lower) &&
    lower.length > 4
  ) {
    return 'noun';
  }
  if (/(?:ed|ing)$/.test(lower) && lower.length > 4) {
    return 'verb';
  }
  // -al is ambiguous (final, manual, central are adjectives; arrival,
  // proposal are nouns). Default to adjective for -al as it's the more
  // common content sense.
  if (/al$/.test(lower) && lower.length > 4) {
    return 'adjective';
  }
  // Default: unknown content words are most often nouns in English.
  return 'noun';
}

// Tokenize `text` into word entries with position. Words = runs of
// [A-Za-z'-]; everything else is whitespace/punctuation and is skipped.
export function taggedTokens(text) {
  if (!text) return [];
  const tokens = [];
  const re = /[A-Za-z][A-Za-z'-]*/g;
  let m = re.exec(text);
  while (m !== null) {
    const word = m[0];
    tokens.push({
      word,
      pos: classifyWord(word),
      start: m.index,
      end: m.index + word.length,
    });
    m = re.exec(text);
  }
  return tokens;
}

// Pick `cap` items from `arr`, evenly spaced by index. Used to keep the
// recall task tractable when a POS rung would otherwise mask too many
// words (e.g. 26 nouns in a 50-word paragraph). Returns the original
// array when its length is already at or below the cap.
export function sampleEvenly(arr, cap) {
  if (arr.length <= cap) return arr;
  const out = [];
  const step = arr.length / cap;
  for (let i = 0; i < cap; i += 1) {
    out.push(arr[Math.floor(i * step)]);
  }
  return out;
}

// Build a `${...}`-masked variant of `text` by masking every word
// whose tagged POS is in `posSet`. Preserves all surrounding whitespace
// and punctuation so the rendered output reads identically except for
// the redacted spans.
//
// `options.cap` (default: unlimited) bounds the number of masks per call.
// When the candidate set exceeds the cap, picks evenly-spaced indices so
// masking stays spatially distributed across the paragraph.
export function buildPosMask(text, posSet, options = {}) {
  if (!text) return '';
  const { cap = Infinity } = options;
  const tagged = taggedTokens(text);
  let masks = tagged.filter((t) => posSet.has(t.pos));
  if (masks.length === 0) return text;
  if (cap < masks.length) {
    masks = sampleEvenly(masks, cap);
  }
  let out = '';
  let cursor = 0;
  masks.forEach((t) => {
    out += text.slice(cursor, t.start);
    // eslint-disable-next-line no-template-curly-in-string
    out += `\${${t.word}}`;
    cursor = t.end;
  });
  out += text.slice(cursor);
  return out;
}
