/**
 * LearningTopic.ts
 *
 * Data models for the AI Learning Companion Framework.
 * Defines interfaces for Learning Topics, Plans, Sessions, and Performance tracking.
 *
 * Core Entities:
 * - LearningTopic: User's learning goal (e.g., "GRE Vocabulary", "Python Basics")
 * - LearningPlan: AI-generated curriculum with phases and daily goals
 * - LearningSession: Single study session with performance data
 * - LearningItemPerformance: Per-item performance tracking
 */

import {
  DomainType,
  TopicStatus,
  SessionType,
  DifficultyLevel,
  TopicSourceType,
  ContentType,
  AssessmentMethod,
} from './LearningDomains';

// =============================================================================
// LEARNING TOPIC - User's learning goal
// =============================================================================

/**
 * A Learning Topic represents a user's learning goal.
 * It's an instance of a domain type with specific content and progress tracking.
 *
 * Examples:
 * - "GRE Vocabulary" (domain: vocabulary)
 * - "Python Programming" (domain: skill)
 * - "The Art of War - Book Study" (domain: knowledge)
 * - "Japanese Language" (domain: language)
 * - "Calculus I" (domain: math)
 */
export interface LearningTopic {
  id: string;
  userId: number;

  // Core identification
  name: string;
  description: string | null;
  domainType: DomainType;

  // Source linkage (optional - topic can be linked to existing content)
  sourceType: TopicSourceType | null;
  sourceId: string | null; // Book ID, vocabulary set ID, URL, etc.

  // Learning configuration
  targetDate: Date | null; // Target completion date
  dailyTimeMinutes: number; // Daily study time goal
  difficulty: DifficultyLevel | 'auto'; // Starting difficulty or auto-detect

  // Status and progress
  status: TopicStatus;
  progressPercent: number; // 0-100
  masteredItems: number;
  totalItems: number;

  // Engagement tracking
  streakDays: number;
  lastStudiedAt: Date | null;

  // Timestamps
  createdAt: Date;
  updatedAt: Date | null;
}

/**
 * Input for creating a new learning topic
 */
export interface CreateLearningTopicInput {
  name: string;
  description?: string;
  domainType: DomainType;
  sourceType?: TopicSourceType;
  sourceId?: string;
  targetDate?: Date;
  dailyTimeMinutes?: number;
  difficulty?: DifficultyLevel | 'auto';
}

/**
 * Input for updating a learning topic
 */
export interface UpdateLearningTopicInput {
  name?: string;
  description?: string;
  targetDate?: Date | null;
  dailyTimeMinutes?: number;
  difficulty?: DifficultyLevel | 'auto';
  status?: TopicStatus;
}

// =============================================================================
// LEARNING PLAN - AI-generated curriculum
// =============================================================================

/**
 * A Learning Plan is an AI-generated curriculum for achieving a learning topic.
 * It contains phases, milestones, daily goals, and item scheduling.
 */
export interface LearningPlan {
  id: string;
  topicId: string;
  userId: number;

  // Plan structure (stored as JSON)
  planData: LearningPlanData;

  // Progress tracking
  currentPhase: number;
  currentDay: number;
  status: 'active' | 'completed' | 'paused' | 'abandoned';

  // Timestamps
  startedAt: Date | null;
  completedAt: Date | null;
  createdAt: Date;
  updatedAt: Date | null;
}

/**
 * The structured plan data generated by AI
 */
export interface LearningPlanData {
  // Overview
  overview: string;
  estimatedDuration: number; // days
  totalPhases: number;

  // Phases
  phases: LearningPhase[];

  // Learning items to be covered
  items: LearningItem[];

  // Daily schedule template
  dailySchedule: DailySchedule;

  // Milestones
  milestones: Milestone[];

  // AI recommendations
  recommendations: string[];

  // Assessment checkpoints
  assessmentCheckpoints: AssessmentCheckpoint[];
}

/**
 * A phase within a learning plan
 */
export interface LearningPhase {
  phaseNumber: number;
  name: string;
  description: string;
  durationDays: number;
  focusAreas: string[];
  objectives: string[];
  contentTypes: ContentType[];
  assessmentMethods: AssessmentMethod[];
}

/**
 * A single learning item (concept, word, skill, etc.)
 */
export interface LearningItem {
  id: string;
  type: string; // Domain-specific type (e.g., "word", "concept", "technique")
  name: string;
  description?: string;
  difficulty: DifficultyLevel;
  phase: number; // Which phase this item belongs to

  // Dependencies
  prerequisites: string[]; // IDs of prerequisite items

  // Scheduling
  scheduledDay?: number;
  estimatedTimeMinutes: number;

  // Status (updated during learning)
  status: 'pending' | 'learning' | 'reviewing' | 'mastered';
  masteryLevel: number; // 0-100

  // For spaced repetition
  lastReviewedAt?: Date;
  nextReviewAt?: Date;
  reviewCount: number;
  correctStreak: number;
}

/**
 * Daily schedule template
 */
export interface DailySchedule {
  recommendedSessions: number;
  sessionDurationMinutes: number;

  // Distribution of time
  newItemsPercent: number; // % time on new items
  reviewPercent: number; // % time on review
  practicePercent: number; // % time on practice/exercises

  // Suggested activities
  suggestedActivities: string[];
}

/**
 * Milestone in the learning journey
 */
export interface Milestone {
  id: string;
  name: string;
  description: string;
  targetDay: number;
  targetPhase: number;
  criteria: {
    itemsMastered?: number;
    conceptsCovered?: number;
    assessmentScore?: number;
    streakDays?: number;
  };
  reward?: string; // Gamification: achievement/badge
  completed: boolean;
  completedAt?: Date;
}

/**
 * Assessment checkpoint
 */
export interface AssessmentCheckpoint {
  day: number;
  phase: number;
  type: 'quiz' | 'review' | 'project' | 'comprehensive';
  assessmentMethods: AssessmentMethod[];
  passingScore: number;
  description: string;
}

/**
 * Input for creating a learning plan
 */
export interface CreateLearningPlanInput {
  topicId: string;
  // Optional AI hints
  focusAreas?: string[];
  preferredPace?: 'relaxed' | 'moderate' | 'intensive';
  existingKnowledge?: string[];
  learningStyle?: 'visual' | 'reading' | 'hands-on' | 'mixed';
}

// =============================================================================
// LEARNING SESSION - Single study session
// =============================================================================

/**
 * A Learning Session represents a single study interaction.
 * Tracks what was studied, how long, and performance metrics.
 */
export interface LearningSession {
  id: string;
  planId: string | null; // Can be null for ad-hoc sessions
  topicId: string;
  userId: number;

  // Session info
  sessionType: SessionType;
  startedAt: Date;
  completedAt: Date | null;
  durationMinutes: number | null;

  // Performance metrics
  itemsReviewed: number;
  itemsCorrect: number;
  itemsNew: number;

  // Detailed session data (JSON)
  sessionData: SessionData | null;
}

/**
 * Detailed session data
 */
export interface SessionData {
  // Items studied in this session
  itemResults: ItemResult[];

  // Session quality metrics
  focusScore?: number; // 0-1, based on response times and consistency
  engagementLevel?: 'low' | 'medium' | 'high';

  // Notes from AI
  aiObservations?: string[];
  suggestedNextSteps?: string[];

  // For specific session types
  quizResults?: QuizSessionResults;
  practiceResults?: PracticeSessionResults;
}

/**
 * Result for a single item in a session
 */
export interface ItemResult {
  itemId: string;
  itemType: string;
  wasCorrect: boolean;
  responseTimeMs: number;
  confidenceLevel?: 1 | 2 | 3 | 4 | 5; // User self-reported
  mistakeType?: string; // AI-categorized mistake
  attempt: number; // nth attempt on this item
}

/**
 * Quiz-specific session results
 */
export interface QuizSessionResults {
  totalQuestions: number;
  correctAnswers: number;
  score: number; // percentage
  timeSpentMinutes: number;
  questionResults: {
    questionId: string;
    wasCorrect: boolean;
    selectedAnswer: string;
    correctAnswer: string;
    timeSpentSeconds: number;
  }[];
}

/**
 * Practice-specific session results
 */
export interface PracticeSessionResults {
  exercisesCompleted: number;
  exercisesCorrect: number;
  difficultyLevel: DifficultyLevel;
  skillsImproved: string[];
}

/**
 * Input for creating a learning session
 */
export interface CreateLearningSessionInput {
  topicId: string;
  planId?: string;
  sessionType: SessionType;
}

/**
 * Input for completing a learning session
 */
export interface CompleteLearningSessionInput {
  sessionId: string;
  itemsReviewed: number;
  itemsCorrect: number;
  itemsNew: number;
  sessionData?: SessionData;
}

// =============================================================================
// LEARNING ITEM PERFORMANCE - Per-item tracking
// =============================================================================

/**
 * Tracks performance on individual learning items over time.
 * Used for spaced repetition scheduling and adaptive difficulty.
 */
export interface LearningItemPerformance {
  id: number;
  userId: number;
  topicId: string;

  // Item identification
  itemId: string;
  itemType: string; // "word", "concept", "problem", etc.

  // Review event
  reviewedAt: Date;
  wasCorrect: boolean;
  responseTimeMs: number | null;
  confidenceLevel: number | null; // 1-5

  // Error analysis
  mistakeType: string | null;

  // Difficulty tracking
  difficultyRating: number | null; // 1-5, user perceived difficulty

  // Mastery change
  masteryBefore: number | null;
  masteryAfter: number | null;

  // Session reference
  sessionId: string | null;
}

/**
 * Input for recording item performance
 */
export interface RecordItemPerformanceInput {
  topicId: string;
  itemId: string;
  itemType: string;
  wasCorrect: boolean;
  responseTimeMs?: number;
  confidenceLevel?: number;
  mistakeType?: string;
  difficultyRating?: number;
  sessionId?: string;
}

// =============================================================================
// AGGREGATED STATISTICS
// =============================================================================

/**
 * Statistics for a learning topic
 */
export interface TopicStatistics {
  topicId: string;

  // Overall progress
  totalItems: number;
  masteredItems: number;
  inProgressItems: number;
  pendingItems: number;
  progressPercent: number;

  // Time stats
  totalTimeMinutes: number;
  averageSessionMinutes: number;
  totalSessions: number;

  // Performance
  overallAccuracy: number; // percentage
  averageResponseTimeMs: number;
  currentStreak: number;
  longestStreak: number;

  // Recent activity
  lastSessionAt: Date | null;
  sessionsLast7Days: number;
  itemsReviewedLast7Days: number;

  // Phase progress (if plan exists)
  currentPhase?: number;
  totalPhases?: number;
  currentDay?: number;
  estimatedDaysRemaining?: number;

  // Items due for review
  itemsDueToday: number;
  itemsOverdue: number;
}

/**
 * Daily activity summary
 */
export interface DailyActivity {
  date: Date;
  topicId: string;
  sessionsCount: number;
  totalMinutes: number;
  itemsReviewed: number;
  itemsCorrect: number;
  newItemsLearned: number;
  accuracy: number;
}

/**
 * Weakness analysis for a topic
 */
export interface WeaknessAnalysis {
  topicId: string;

  // Items with lowest mastery
  weakItems: {
    itemId: string;
    itemName: string;
    masteryLevel: number;
    recentAccuracy: number;
    commonMistakeTypes: string[];
  }[];

  // Patterns identified
  patterns: {
    pattern: string;
    description: string;
    affectedItems: string[];
    suggestedAction: string;
  }[];

  // Recommendations
  recommendations: string[];
}

// =============================================================================
// TYPE GUARDS AND UTILITIES
// =============================================================================

/**
 * Check if a topic is active (can be studied)
 */
export function isTopicActive(topic: LearningTopic): boolean {
  return topic.status === TopicStatus.ACTIVE;
}

/**
 * Check if a topic has an active plan
 */
export function topicHasPlan(
  topic: LearningTopic,
  plan: LearningPlan | null
): plan is LearningPlan {
  return plan !== null && plan.status === 'active';
}

/**
 * Calculate days until target date
 */
export function daysUntilTarget(topic: LearningTopic): number | null {
  if (!topic.targetDate) return null;
  const now = new Date();
  const target = new Date(topic.targetDate);
  const diffTime = target.getTime() - now.getTime();
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
}

/**
 * Calculate accuracy percentage from session data
 */
export function calculateSessionAccuracy(session: LearningSession): number {
  if (session.itemsReviewed === 0) return 0;
  return (session.itemsCorrect / session.itemsReviewed) * 100;
}

/**
 * Get next review date based on spaced repetition
 * Using a simplified SM-2 like algorithm
 */
export function calculateNextReview(
  correctStreak: number,
  wasCorrect: boolean
): Date {
  const now = new Date();
  let intervalDays: number;

  if (!wasCorrect) {
    // Reset to 1 day on incorrect
    intervalDays = 1;
  } else {
    // Exponential growth based on streak
    switch (correctStreak) {
      case 0:
        intervalDays = 1;
        break;
      case 1:
        intervalDays = 1;
        break;
      case 2:
        intervalDays = 3;
        break;
      case 3:
        intervalDays = 7;
        break;
      case 4:
        intervalDays = 14;
        break;
      case 5:
        intervalDays = 30;
        break;
      default:
        intervalDays = Math.min(90, 30 * Math.pow(1.5, correctStreak - 5));
    }
  }

  return new Date(now.getTime() + intervalDays * 24 * 60 * 60 * 1000);
}

/**
 * Generate a unique ID for learning entities
 */
export function generateLearningId(prefix: string = 'learn'): string {
  const timestamp = Date.now().toString(36);
  const randomPart = Math.random().toString(36).substring(2, 8);
  return `${prefix}_${timestamp}_${randomPart}`;
}
