/**
 * UniversalLearningPoint.ts
 *
 * A universal abstraction for any learnable content represented as cards.
 * This model bridges the gap between different content types (vocabulary, concepts,
 * formulas, facts) and the spaced repetition system.
 *
 * Design Philosophy:
 * - Any learning goal decomposes into atomic "learning points"
 * - Each learning point is represented as a card (front/back)
 * - Cards can be linked to source chunks and concepts
 * - Supports both manual creation and AI generation
 */

import { DomainType, DifficultyLevel, ContentType } from './LearningDomains';

// =============================================================================
// LEARNING POINT TYPES
// =============================================================================

/**
 * Type of learning point - determines card structure and study behavior
 */
export type LearningPointType =
  | 'word' // Vocabulary word
  | 'concept' // Abstract concept/idea
  | 'formula' // Mathematical formula
  | 'rule' // Grammar/logic rule
  | 'fact' // Historical fact, date, etc.
  | 'technique' // Skill or procedure
  | 'example' // Worked example
  | 'problem' // Practice problem
  | 'definition' // Term definition
  | 'relationship' // Connection between concepts
  | 'quote' // Notable quote
  | 'code' // Code snippet
  | 'custom'; // User-defined type

/**
 * Source type - where did this learning point come from?
 */
export type LearningPointSourceType =
  | 'book_chunk' // Extracted from book chunk
  | 'vocabulary' // From vocabulary table
  | 'note' // From user note
  | 'quiz' // From quiz problem
  | 'highlight' // From book highlight
  | 'url' // From web content
  | 'manual' // Manually created by user
  | 'ai_generated'; // Generated by AI

/**
 * Status of a learning point in the learning plan
 */
export type LearningPointStatus =
  | 'pending' // Not yet started
  | 'learning' // Currently learning (new)
  | 'reviewing' // In review cycle
  | 'mastered'; // Fully learned

// =============================================================================
// CARD CONTENT
// =============================================================================

/**
 * Content for one side of a learning card
 * Supports multiple content types for rich learning experiences
 */
export interface CardContent {
  /** Main text content (supports markdown) */
  text: string;

  /** Optional rich HTML content */
  html?: string;

  /** Optional image (URL or base64) */
  image?: string;

  /** Optional audio URL (for pronunciation) */
  audio?: string;

  /** Optional LaTeX formula */
  latex?: string;

  /** Optional code snippet */
  code?: {
    language: string;
    content: string;
  };
}

/**
 * Extended content for specific learning point types
 */
export interface LearningPointExtras {
  // For vocabulary
  pronunciation?: string;
  partOfSpeech?: string;
  etymology?: string;
  synonyms?: string[];
  antonyms?: string[];
  exampleSentences?: string[];

  // For formulas
  variables?: { symbol: string; meaning: string }[];
  derivation?: string;
  applications?: string[];

  // For concepts
  keyPoints?: string[];
  commonMisconceptions?: string[];
  relatedConcepts?: string[];

  // For problems
  solution?: string;
  hints?: string[];
  difficulty?: number; // 1-10

  // For code
  explanation?: string;
  output?: string;
  timeComplexity?: string;
  spaceComplexity?: string;

  // Generic
  tags?: string[];
  notes?: string;
}

// =============================================================================
// UNIVERSAL LEARNING POINT
// =============================================================================

/**
 * UniversalLearningPoint - The core abstraction for any learnable content
 *
 * This interface unifies different content types into a single card-based
 * format that works with spaced repetition systems.
 */
export interface UniversalLearningPoint {
  // === Identification ===

  /** Unique identifier (UUID) */
  id: string;

  /** User who owns this learning point */
  userId: number;

  /** Type of learning point */
  itemType: LearningPointType;

  /** Domain this belongs to */
  domainType: DomainType;

  // === Card Content ===

  /** Title/name of the learning point */
  title: string;

  /** Front of card (question/prompt) */
  front: CardContent;

  /** Back of card (answer/explanation) */
  back: CardContent;

  /** Domain-specific extra fields */
  extras?: LearningPointExtras;

  // === Metadata ===

  /** Difficulty level */
  difficulty: DifficultyLevel;

  /** Estimated time to learn (minutes) */
  estimatedTimeMinutes: number;

  /** User-defined tags */
  tags?: string[];

  // === Learning Mechanics ===

  /** IDs of prerequisite learning points */
  prerequisites?: string[];

  /** IDs of related learning points */
  relatedItems?: string[];

  /** Content types this point teaches */
  contentTypes?: ContentType[];

  // === Status (managed by learning plan) ===

  /** Current learning status */
  status: LearningPointStatus;

  /** Mastery level 0-100 */
  masteryLevel: number;

  /** Day in plan when this should be introduced */
  scheduledDay?: number;

  /** Phase in plan this belongs to */
  phase?: number;

  // === Spaced Repetition ===

  /** Link to sr_item table for FSRS tracking */
  srItemId?: string;

  /** Last review timestamp */
  lastReviewedAt?: string;

  /** Next scheduled review */
  nextReviewAt?: string;

  /** Number of times reviewed */
  reviewCount: number;

  /** Consecutive correct answers */
  correctStreak: number;

  // === Source Reference ===

  /** Where this learning point came from */
  sourceType?: LearningPointSourceType;

  /** ID in source table (e.g., vocabulary.id, note_json.id) */
  sourceId?: string;

  /** Additional source context (page number, chapter, URL path) */
  sourceContext?: string;

  /** ID of the chunk this was extracted from (if from book) */
  chunkId?: string;

  // === AI Generation ===

  /** AI provider used for generation */
  generatedBy?: string;

  /** Prompt used (for regeneration) */
  generationPrompt?: string;

  /** AI confidence score 0-1 */
  confidence?: number;

  // === Timestamps ===

  createdAt: string;
  updatedAt?: string;
}

// =============================================================================
// INPUT/OUTPUT TYPES
// =============================================================================

/**
 * Input for creating a learning point
 */
export interface CreateLearningPointInput {
  itemType: LearningPointType;
  domainType: DomainType;
  title: string;
  front: CardContent;
  back: CardContent;
  extras?: LearningPointExtras;
  difficulty?: DifficultyLevel;
  estimatedTimeMinutes?: number;
  tags?: string[];
  prerequisites?: string[];
  sourceType?: LearningPointSourceType;
  sourceId?: string;
  sourceContext?: string;
  chunkId?: string;
}

/**
 * Input for bulk creating learning points
 */
export interface BulkCreateLearningPointInput {
  items: CreateLearningPointInput[];
  topicId?: string;
  planId?: string;
}

/**
 * Input for updating a learning point
 */
export interface UpdateLearningPointInput {
  title?: string;
  front?: CardContent;
  back?: CardContent;
  extras?: LearningPointExtras;
  difficulty?: DifficultyLevel;
  tags?: string[];
  status?: LearningPointStatus;
  masteryLevel?: number;
}

/**
 * Result of reviewing a learning point
 */
export interface LearningPointReviewResult {
  learningPointId: string;
  wasCorrect: boolean;
  responseTimeMs?: number;
  confidenceLevel?: 1 | 2 | 3 | 4 | 5;
  newMasteryLevel: number;
  newStatus: LearningPointStatus;
  nextReviewAt: string;
}

// =============================================================================
// BOOK CHUNK (for Neo4j storage)
// =============================================================================

/**
 * A chunk of book content stored in Neo4j
 */
export interface BookChunk {
  /** Unique identifier */
  id: string;

  /** Reference to book in SQLite */
  bookId: string;

  /** Owner */
  userId: number;

  /** Chunk text content */
  text: string;

  /** Order in book */
  chunkIndex: number;

  /** Page number (for PDF) */
  pageNum?: number;

  /** CFI location (for EPUB) */
  cfi?: string;

  /** Chapter/section title */
  sectionTitle?: string;

  /** Embedding vector */
  embedding?: number[];

  /** Embedding model used */
  embeddingModel?: string;

  /** Summary generated by AI */
  summary?: string;

  /** Concepts mentioned in this chunk (IDs) */
  conceptIds?: string[];

  createdAt: string;
}

/**
 * Input for creating book chunks
 */
export interface CreateBookChunkInput {
  bookId: string;
  text: string;
  chunkIndex: number;
  pageNum?: number;
  cfi?: string;
  sectionTitle?: string;
}

// =============================================================================
// KEY CONCEPT (extracted from book metadata)
// =============================================================================

/**
 * A key concept extracted from book metadata/TOC
 * This is the cheap extraction done at import time
 */
export interface KeyConcept {
  /** Unique identifier */
  id: string;

  /** Book this concept belongs to */
  bookId: string;

  /** Concept name */
  name: string;

  /** Brief description */
  description?: string;

  /** Category/type */
  category?: string;

  /** Importance score 0-1 */
  importance?: number;

  /** Embedding vector (for similarity matching) */
  embedding?: number[];

  /** Chapter/section where primarily discussed */
  primarySection?: string;

  /** Chunks that mention this concept (derived) */
  chunkIds?: string[];

  /** Related concepts (derived from co-occurrence) */
  relatedConceptIds?: string[];

  createdAt: string;
}

/**
 * Input for extracting key concepts from book
 */
export interface ExtractKeyConceptsInput {
  bookId: string;
  title: string;
  author?: string;
  description?: string;
  tableOfContents?: string[];
  sampleText?: string; // First/last paragraphs
}

/**
 * Result of key concept extraction
 */
export interface ExtractKeyConceptsResult {
  concepts: Omit<KeyConcept, 'id' | 'bookId' | 'createdAt' | 'embedding'>[];
  suggestedDomain: DomainType;
  estimatedDifficulty: DifficultyLevel;
}

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/**
 * Generate a unique ID for learning entities
 */
export function generateLearningPointId(): string {
  const timestamp = Date.now().toString(36);
  const randomPart = Math.random().toString(36).substring(2, 8);
  return `lp_${timestamp}_${randomPart}`;
}

/**
 * Generate a unique ID for book chunks
 */
export function generateChunkId(): string {
  const timestamp = Date.now().toString(36);
  const randomPart = Math.random().toString(36).substring(2, 8);
  return `chunk_${timestamp}_${randomPart}`;
}

/**
 * Generate a unique ID for concepts
 */
export function generateConceptId(): string {
  const timestamp = Date.now().toString(36);
  const randomPart = Math.random().toString(36).substring(2, 8);
  return `concept_${timestamp}_${randomPart}`;
}

/**
 * Create a simple text card from vocabulary
 */
export function createVocabularyCard(
  word: string,
  definition: string,
  extras?: Partial<LearningPointExtras>
): Omit<UniversalLearningPoint, 'id' | 'userId' | 'createdAt'> {
  return {
    itemType: 'word',
    domainType: DomainType.VOCABULARY,
    title: word,
    front: { text: word },
    back: { text: definition },
    extras: extras as LearningPointExtras,
    difficulty: DifficultyLevel.INTERMEDIATE,
    estimatedTimeMinutes: 1,
    status: 'pending',
    masteryLevel: 0,
    reviewCount: 0,
    correctStreak: 0,
  };
}

/**
 * Create a concept card
 */
export function createConceptCard(
  name: string,
  explanation: string,
  keyPoints?: string[]
): Omit<UniversalLearningPoint, 'id' | 'userId' | 'createdAt'> {
  return {
    itemType: 'concept',
    domainType: DomainType.KNOWLEDGE,
    title: name,
    front: { text: `What is ${name}?` },
    back: { text: explanation },
    extras: keyPoints ? { keyPoints } : undefined,
    difficulty: DifficultyLevel.INTERMEDIATE,
    estimatedTimeMinutes: 3,
    status: 'pending',
    masteryLevel: 0,
    reviewCount: 0,
    correctStreak: 0,
  };
}

/**
 * Create a formula card
 */
export function createFormulaCard(
  name: string,
  formula: string,
  explanation: string,
  variables?: { symbol: string; meaning: string }[]
): Omit<UniversalLearningPoint, 'id' | 'userId' | 'createdAt'> {
  return {
    itemType: 'formula',
    domainType: DomainType.MATH,
    title: name,
    front: { text: `What is the formula for ${name}?` },
    back: { text: explanation, latex: formula },
    extras: variables ? { variables } : undefined,
    difficulty: DifficultyLevel.INTERMEDIATE,
    estimatedTimeMinutes: 2,
    status: 'pending',
    masteryLevel: 0,
    reviewCount: 0,
    correctStreak: 0,
  };
}

/**
 * Calculate mastery level change after review
 */
export function calculateMasteryChange(
  currentMastery: number,
  wasCorrect: boolean,
  correctStreak: number
): number {
  if (wasCorrect) {
    // Increase mastery, with bonus for streaks
    const increase = 10 + Math.min(correctStreak * 2, 10);
    return Math.min(100, currentMastery + increase);
  } else {
    // Decrease mastery on incorrect
    const decrease = 15;
    return Math.max(0, currentMastery - decrease);
  }
}

/**
 * Determine status from mastery level
 */
export function getStatusFromMastery(
  masteryLevel: number,
  reviewCount: number
): LearningPointStatus {
  if (masteryLevel >= 90 && reviewCount >= 5) {
    return 'mastered';
  } else if (reviewCount > 0) {
    return 'reviewing';
  } else if (masteryLevel > 0) {
    return 'learning';
  }
  return 'pending';
}

/**
 * Default difficulty settings per learning point type
 */
export const DEFAULT_DIFFICULTY_BY_TYPE: Record<
  LearningPointType,
  DifficultyLevel
> = {
  word: DifficultyLevel.BEGINNER,
  definition: DifficultyLevel.BEGINNER,
  fact: DifficultyLevel.BEGINNER,
  concept: DifficultyLevel.INTERMEDIATE,
  rule: DifficultyLevel.INTERMEDIATE,
  quote: DifficultyLevel.BEGINNER,
  example: DifficultyLevel.INTERMEDIATE,
  technique: DifficultyLevel.INTERMEDIATE,
  formula: DifficultyLevel.ADVANCED,
  problem: DifficultyLevel.INTERMEDIATE,
  relationship: DifficultyLevel.INTERMEDIATE,
  code: DifficultyLevel.INTERMEDIATE,
  custom: DifficultyLevel.INTERMEDIATE,
};

/**
 * Default time estimates per learning point type (minutes)
 */
export const DEFAULT_TIME_BY_TYPE: Record<LearningPointType, number> = {
  word: 1,
  definition: 1,
  fact: 1,
  concept: 3,
  rule: 2,
  quote: 1,
  example: 3,
  technique: 5,
  formula: 2,
  problem: 5,
  relationship: 2,
  code: 3,
  custom: 2,
};
